### ISSUE TITLE
Roadmap to 1.0(?)

### ISSUE THREAD

**Issue by NamesMark** [NamesMark/apiel#3]
- [ ] pervasion
- [ ] each ([M](https://help.dyalog.com/18.0/index.htm#Language/Primitive%20Operators/Each%20with%20Monadic%20Operand.htm), [D](https://help.dyalog.com/18.0/index.htm#Language/Primitive%20Operators/Each%20with%20Dyadic%20Operand.htm))
- [ ] add Array to Val
- [ ] flat array for infinite recursion
- [ ] implement functions
- [ ] implement assign
- [ ] high minus
- [ ] shape, reshape
- [ ] reverse, rotate
- [ ] transpose
- [ ] ravel
- [ ] inner/outer product
- [ ] strings, chars
- [ ] bool operations
- [ ] matrix operations
- [ ] binary operations
- [ ] [Replicate](https://help.dyalog.com/18.0/index.htm#Language/Primitive%20Functions/Replicate.htm), [Expand](https://help.dyalog.com/18.0/index.htm#Language/Primitive%20Functions/Expand.htm), [Scan](https://help.dyalog.com/18.0/index.htm#Language/Primitive%20Operators/Scan.htm), [Replicate First](https://help.dyalog.com/18.0/index.htm#Language/Primitive%20Functions/Replicate%20First.htm), [Reduce First](https://help.dyalog.com/18.0/index.htm#Language/Primitive%20Operators/Reduce%20First.htm), [Expand First](https://help.dyalog.com/18.0/index.htm#Language/Primitive%20Functions/Expand%20First.htm), [Scan First](https://help.dyalog.com/18.0/index.htm#Language/Primitive%20Operators/Scan%20First.htm)
- [ ] ↑↓⊂⊃⊆⌷⍋⍒  😮‍💨

**Comment by NamesMark** [comment]
Implemented in #4
